### ISSUE TITLE
grug: typed events

### ISSUE THREAD

**Issue by larry0x** [left-curve/left-curve#26]
This is a brainstorm on how to introduce types to events.

In Tendermint, events are simply a name (`type`) plus a list of key-value pairs (`attributes`):

```typescript
type TmEvent = {
  type: string;
  attributes: { key: string; value: string; }[];
};
```

CosmWasm defines events [the same way](https://github.com/CosmWasm/cosmwasm/blob/v2.0.4/packages/std/src/results/events.rs#L15-L27), so that events emitted by contracts can be easily converted into `TmEvent`.

However, KV pairs aren't typed. They are difficult to work with for indexers.

We want events to be typed, and can be parsed into Rust and TypeScript types.

One approach to achieve this (used by Penumbra) is to define events as Protobuf types. An event is serialized into bytes as a Protobuf `Any`, which includes its `type_url`.

However, I hate Protobuf and rather not use it. Instead I want a pure Rust solution.

Current idea is to define events like this:

```rust
pub struct Event {
    pub type_name: String,
    pub data: serde_json::Value,
}

impl Event {
    pub fn new<T: Serialize>(event: &T) -> StdResult<Self> {
        Ok(Self {
            type_name: std::any::type_name::<T>().to_string(),
            data: serde_json::to_value(event)?,
        })
    }
}

pub struct Response {
    pub msgs: Vec<Submessage>,
    pub events: Vec<Event>,
}

impl Response {
    pub fn add_event<T: Serialize>(mut self, event: &T) -> StdResult<Self> {
        self.event.push(Event::new(event)?);
        Ok(self)
    }
}
```

Define and emit custom errors in contracts:

```rust
// Each contract defines its own event type
pub enum BankEvent {
    Transfer { sender: Addr, receiver: Addr, coins: Coins },
    Mint { /* ... */ },
    Burn { /* ... */ },
}

pub fn transfer(ctx: MutableCtx, sender: Addr, reciver: Addr, coins: Coins) -> StdResult<Response> {
    // transfer logic here
    // ...

    // Add the event in `Response`
    Response::new()
        .add_message(/* ... */)
        .add_event(BankEvent::Transfer { sender, receiver, coins })
}
```

We need to eventually convert `Event` to Tendermint event (`TmEvent`). I propose it be converted this way:

```json
{
  "type": "execute",
  "attributes": [
    {
      "key": "contract_address",
      "value": "..."
    },
    {
      "key": "contract_event",
      "value": "{\"type_name\":\"grug_bank::BankEvent\",\"data\":{\"transfer\":\"sender\":\"...\",\"receiver\":\"...\",\"coins\":\"...\"}}"
    },
    {
      "key": "contract_event",
      "value": "{\"type_name\":\"grug_bank::BankEvent\",\"data\":{\"mint\":{}}}"
    }
  ]
}
```

- `type` is the transaction type, can be "instantiate", "execute", "migrate", ...
- There should be one and only one attribute, typically the first one, with the key `contract_address`, that records the contract address.
- There should be zero or more attributes with the key `contract_event`, whose value contains the JSON serialized `Event`.

The question is, now we know that the type name is `grug_bank::BankEvent`, how to we parse the `data` into a `grug_bank::BankEvent`? Rust doesn't support runtime reflection, so the best approach maybe is to create a registry of types indexed by their type names (similar to `InterfaceRegistry` in Cosmos SDK).

**Comment by larry0x** [comment]
Can perhaps use [`std::any::TypeId`](https://doc.rust-lang.org/std/any/struct.TypeId.html) instead of a `String`

**Comment by penso** [comment]
The lack of introspection in Rust makes protobuf actually nice, so you don't need a registry of types which might become messy quickly and not manageable on the long run, when Grug gets a lot of use from different parties. It also make it easy for indexer in other languages.

**Comment by larry0x** [comment]
@penso How would you handle a typed event encoded in Protobuf? I think you can only deserialize it into a `Box<dyn prost::Message>` instead the actual Rust type?

**Comment by penso** [comment]
It's a little complex, and I only care about a `json` version of the cosmos messages and not specifics but the summary is:

1. Put all protobuf files in a sub-directory

2. Within a specific sub-crate, I use `prost-build` and `tonic-build` to generate (compile) Rust structs in Rust files from the protobuf files and important I add `serde::Serialize` tags for me to convert those into `JSON`. I also add some `#[skip]` in some fields I don't care.

```rust
    prost_build
        .out_dir(&out_dir)
        .extern_path(".google.protobuf.Any", "crate::Any")
        .extern_path(
            ".cosmwasm.wasm.v1.SudoContractProposal",
            "crate::SudoContractProposal",
        )
        .file_descriptor_set_path(out_dir.join("file_descriptor_set.bin"))
        .enable_type_names()
        .include_file(Path::new("_includes.rs"));

    let dirs = args
        .sources
        .into_iter()
        .map(|t| current_dir.join(t))
        .collect::<Vec<_>>();
    let files = all_proto_files(dirs.clone());

    prost_build.compile_protos(&files, &dirs)?;

    let file_descriptor_set_bytes = fs::read(out_dir.join("file_descriptor_set.bin")).unwrap();
    let file_descriptor_set = FileDescriptorSet::decode(&file_descriptor_set_bytes[..]).unwrap();

    generate_handlers_map(&out_dir, &file_descriptor_set);
```

3. Using the `file_descriptor_set.bin` file and using `syn` and `quote!` I generate code to parse those structs:

```rust
pub fn google_protobuf_descriptor_proto(
    message: &crate::Any,
) -> Result<Box<dyn Message>, prost::DecodeError> {
    let msg = crate::google::protobuf::DescriptorProto::decode(&*message.value)?;
    Ok(Box::new(msg))
}
pub fn google_protobuf_extension_range_options(
    message: &crate::Any,
) -> Result<Box<dyn Message>, prost::DecodeError> {
    let msg = crate::google::protobuf::ExtensionRangeOptions::decode(&*message.value)?;
    Ok(Box::new(msg))
}
pub fn google_protobuf_field_descriptor_proto(
    message: &crate::Any,
) -> Result<Box<dyn Message>, prost::DecodeError> {
    let msg = crate::google::protobuf::FieldDescriptorProto::decode(&*message.value)?;
    Ok(Box::new(msg))
}
...
```
 
I also generate a map handler connecting proto names (String) to a function handler:

```rust
pub fn map() -> HashMap<String, Box<FnHandler>> {
    let mut handlers: HashMap<String, Box<FnHandler>> = HashMap::with_capacity(3289usize);
    handlers.insert(
        crate::google::protobuf::FileDescriptorSet::full_name(),
        Box::new(google_protobuf_file_descriptor_set),
    );
    handlers.insert(
        crate::publicawesome::stargaze::alloc::v1beta1::MsgCreateVestingAccountResponse::full_name(
        ),
        Box::new(publicawesome_stargaze_alloc_v1beta1_msg_create_vesting_account_response),
    );
   ...
}
```

And then something to convert any Message to a `Box<dyn Message>`: 

```rust
    #[typetag::serde(tag = "@type")]
    pub trait Message: std::fmt::Debug {}

        pub fn convert(&self, message: &crate::Any) -> Result<Box<dyn Message>, Error> {
            let Some(handler) = self.handlers.get(message.type_url.trim_start_matches('/')) else {
                return Err(Error::UnknownTypeUrl(message.type_url.clone()));
            };
            Ok(handler(message)?)
        }

```

4. As you wrote, I get a `dyn prost::Message`, and use this code to convert it to `JSON` to store those in `jsonb` data fields:

```rust
    let parsed_dyn_trait = match proto::PARSER_HANDLER.convert(&message) {
        Ok(message) => message,
        Err(error) => {
            warn!(
                "[{}] Error converting message for {}: {:?}",
                block_height, message.type_url, error
            );

            let error_message = match error {
                proto::Error::ProstDecodeError(ref inner_error) => inner_error.to_string(),
                proto::Error::Custom(ref inner_error) => inner_error.clone(), // Assuming this is already a String
                proto::Error::UnknownTypeUrl(ref inner_error) => inner_error.to_string(),
            };

            let message = Message {
                type_url: message.type_url.clone(),
                data: json!({"constellations_error": error_message}),
                ..Default::default()
            };
            return Ok(MessageResult::NotParsed(message));
        }
    };

    let data = match serde_json::to_value(&parsed_dyn_trait) {
        Ok(data) => data,
        Err(error) => {
            warn!(
                "[{}] Error serializing message for {}: {:?}",
                block_height, message.type_url, error
            );
            let message = Message {
                type_url: message.type_url.clone(),
                data: json!({"constellations_error": error.to_string()}),
                ..Default::default()
            };
            return Ok(MessageResult::NotParsed(message));
        }
    };
```

**Comment by larry0x** [comment]
@penso These are really complex stuff... Would it be easier for you, if we provide an "interface registry" like [Cosmos SDK's](https://github.com/cosmos/cosmos-sdk/blob/v0.50.8/codec/types/interface_registry.go#L30) that maps Rust `TypeId`s to deserializer functions?

Like:

```rust
use grug::{Json, StdResult}; // `Json` is an alias to `serde_json::Value`

type Deserializer = Box<dyn Fn(&[u8]) -> StdResult<Json>>;

type InterfaceRegistry = HashMap<TypeId, Deserializer>;
```

With this, given a typed event:

```rust
struct Event {
    type_id: TypeId,
    bytes: Vec<u8>,
}
```

You can just grab the deserializer from the `InterfaceRegistry`, and deserialize it into `serde_json::Value`.

This would be a pure Rust solution, without all the Protobuf complexities.

**Comment by penso** [comment]
You could *but*:

1. This complex stuff I'm doing has to be done anyway, since this is the only way to parse cosmos-sdk messages. Wouldn't save time on that.
2. You doing this means it's harder for any other language needing to interact with your events
3. You could have a crate generating all the code I had to write on my own to do the proto -> rust work.

**Comment by larry0x** [comment]
completed by #350
