### ISSUE TITLE
dango: remove unused key and credential variants

### ISSUE THREAD

**Issue by larry0x** [left-curve/left-curve#264]
We should investigate whether backpack, phantom, and keplr support eip712 signing. If yes, do they use the secp256k1 key or the solana key (ed25519) to sign it?

If yes and they use secp256k1, we can delete the `Key::Ed25519` and `Credential::{Secp256k1,Secp256r1,Ed25519}` variants because we don't plan to support these in the webapp.

**Comment by j0nl1** [comment]
I can confirm that all these wallets support eip-712 and they sign with secp256k1 curve. I delete ed25519 key and credential in #259.

**Comment by larry0x** [comment]
Completed in #259
